{
 "title": "Veeam Backup Tag Report",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "VMware Marseille", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "SLA Gold",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "tag-veeam",
     "select": [
      [
       { "params": [ "name" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "tag::tag", "operator": "=", "value": "Veeam_SLA_Gold" }
     ]
    }
   ]
  },
  {
   "title": "SLA Silver",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "tag-veeam",
     "select": [
      [
       { "params": [ "name" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "tag::tag", "operator": "=", "value": "Veeam_SLA_Silver" }
     ]
    }
   ]
  },
  {
   "title": "SLA Bronze",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "tag-veeam",
     "select": [
      [
       { "params": [ "name" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "tag::tag", "operator": "=", "value": "Veeam_SLA_Bronze" }
     ]
    }
   ]
  },
  {
   "title": "SLA Bronze No Tape",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "tag-veeam",
     "select": [
      [
       { "params": [ "name" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "tag::tag", "operator": "=", "value": "Veeam_SLA_Bronze_-_NoTape" }
     ]
    }
   ]
  },
  {
   "title": "No Veeam Backup",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "tag-veeam",
     "select": [
      [
       { "params": [ "name" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "tag::tag", "operator": "=", "value": "No_Veeam_Bck_Tags" }
     ]
    }
   ]
  },
  {
   "title": "SLA Gold",
   "type": "table",
   "gridPos": { "h": 13, "w": 4, "x": 0, "y": 6 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "tag-veeam",
     "select": [
      [
       { "params": [ "name" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "tag::tag", "operator": "=", "value": "Veeam_SLA_Gold" }
     ]
    }
   ]
  },
  {
   "title": "SLA Silver",
   "type": "table",
   "gridPos": { "h": 13, "w": 4, "x": 5, "y": 6 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "tag-veeam",
     "select": [
      [
       { "params": [ "name" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "tag::tag", "operator": "=", "value": "Veeam_SLA_Silver" }
     ]
    }
   ]
  },
  {
   "title": "SLA Bronze",
   "type": "table",
   "gridPos": { "h": 13, "w": 4, "x": 10, "y": 6 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "tag-veeam",
     "select": [
      [
       { "params": [ "name" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "tag::tag", "operator": "=", "value": "Veeam_SLA_Bronze" }
     ]
    }
   ]
  },
  {
   "title": "SLA Bronze No Tape",
   "type": "table",
   "gridPos": { "h": 13, "w": 4, "x": 15, "y": 6 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "tag-veeam",
     "select": [
      [
       { "params": [ "name" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "tag::tag", "operator": "=", "value": "Veeam_SLA_Bronze_-_NoTape" }
     ]
    }
   ]
  },
  {
   "title": "No Veeam Backup",
   "type": "table",
   "gridPos": { "h": 13, "w": 4, "x": 20, "y": 6 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "tag-veeam",
     "select": [
      [
       { "params": [ "name" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "tag::tag", "operator": "=", "value": "No_Veeam_Bck_Tags" }
     ]
    }
   ]
  },
  { "title": "VMware Lyon", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "SLA Gold",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "tag-veeam-lyon",
     "select": [
      [
       { "params": [ "name" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "tag::tag", "operator": "=", "value": "Veeam_SLA_Gold" }
     ]
    }
   ]
  },
  {
   "title": "SLA Silver",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "tag-veeam",
     "select": [
      [
       { "params": [ "name" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "tag::tag", "operator": "=", "value": "Veeam_SLA_Silver" }
     ]
    }
   ]
  },
  {
   "title": "SLA Bronze",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "tag-veeam-lyon",
     "select": [
      [
       { "params": [ "name" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "tag::tag", "operator": "=", "value": "Veeam_SLA_Bronze" }
     ]
    }
   ]
  },
  {
   "title": "SLA Bronze No Tape",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tag-veeam-lyon",
     "select": [
      [
       { "params": [ "name" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "tag::tag", "operator": "=", "value": "Veeam_SLA_Bronze_-_NoTape" }
     ]
    }
   ]
  },
  {
   "title": "No Veeam Backup without _PRA",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "tag-veeam-lyon",
     "query": "SELECT count(\"name\") FROM \"tag-veeam-lyon\" WHERE (\"tag\"::tag = 'No_Veeam_Bck_Tags') AND \"name\" !~ /_PRA/ AND $timeFilter GROUP BY time(5m) fill(previous)",
     "select": [
      [
       { "params": [ "name" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "tag::tag", "operator": "=", "value": "No_Veeam_Bck_Tags" }
     ]
    }
   ]
  },
  {
   "title": "SLA Gold",
   "type": "table",
   "gridPos": { "h": 13, "w": 4, "x": 0, "y": 25 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "tag-veeam-lyon",
     "select": [
      [
       { "params": [ "name" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "tag::tag", "operator": "=", "value": "Veeam_SLA_Gold" }
     ]
    }
   ]
  },
  {
   "title": "SLA Silver",
   "type": "table",
   "gridPos": { "h": 13, "w": 4, "x": 5, "y": 25 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tag-veeam-lyon",
     "select": [
      [
       { "params": [ "name" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "tag::tag", "operator": "=", "value": "Veeam_SLA_Silver" }
     ]
    }
   ]
  },
  {
   "title": "SLA Bronze",
   "type": "table",
   "gridPos": { "h": 13, "w": 4, "x": 10, "y": 25 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "tag-veeam-lyon",
     "select": [
      [
       { "params": [ "name" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "tag::tag", "operator": "=", "value": "Veeam_SLA_Bronze" }
     ]
    }
   ]
  },
  {
   "title": "SLA Bronze No Tape",
   "type": "table",
   "gridPos": { "h": 13, "w": 4, "x": 15, "y": 25 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tag-veeam-lyon",
     "select": [
      [
       { "params": [ "tag" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "tag::tag", "operator": "=", "value": "Veeam_SLA_Bronze_-_NoTape" }
     ]
    }
   ]
  },
  {
   "title": "No Veeam Backup without _PRA",
   "type": "table",
   "gridPos": { "h": 13, "w": 4, "x": 20, "y": 25 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "tag-veeam-lyon",
     "query": "SELECT distinct(\"name\") FROM \"tag-veeam-lyon\" WHERE (\"tag\"::tag = 'No_Veeam_Bck_Tags') AND \"name\" !~ /_PRA/ AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "name" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "tag::tag", "operator": "=", "value": "No_Veeam_Bck_Tags" }
     ]
    }
   ]
  }
 ]
}